### ISSUE TITLE
Collect data from salinity probe

### ISSUE THREAD

**Issue by BentleySettin** [TinyCamML/ConductivitySensor#8]

**Comment by gracelower** [comment]
When compiling the current code, I am met with the following errors:
- `Ezo_board(uint8_t address);  //Takes I2C address of the device` --- error: explicit type is missing ('int' assumed), error: expected constructor, destructor, or type conversion before ';' 
- `Ezo_board(uint8_t address, const char* name); //Takes I2C address of the device //as well a name of your choice` --- error: explicit type is missing ('int' assumed), error: expected constructor, destructor, or type conversion before ';' 
- exits with error code 2

Possible sources of these errors may be incorrect declaration of classes or functions (i.e. where a constructor, destructor, or type conversion is expected, another entity is coded instead).

Possible solutions to this problem may include accurately declaring / defining classes, member functions, or constructors / destructors, or denoting enums properly.

**Comment by gracelower** [comment]
Solutions to this issue + the updated (compiled, flashed, tested w/ probe) code can be found in pull request https://github.com/TinyCamML/ConductivitySensor/pull/14 (7/24/24)

See this [comment](https://github.com/TinyCamML/ConductivitySensor/pull/14#issuecomment-2250181493) for confirmation (7/25/24)
